### ISSUE TITLE
api endpoint to show all users

### ISSUE THREAD

**Issue by basketbaseb** [basketbaseb/bible-fitbit#17]
return a list of each user registered

**Comment by basketbaseb** [comment]
Going to try and put this in the api/registrations_controller.rb and make a new action called show.
route /api/users/show to this action. think best practice would be to get the data in the model, and format it in the controller. So from the controller call some function in the model?

**Comment by natyconnor** [comment]
Why the registrations_controller? Wouldn't it just be in the users_controller? This is just a normal users index action right? And /api/users/ would route to it. 

For example GroupMe's api just uses GET /groups for all the groups https://dev.groupme.com/docs/v3

Twitter uses one additional sub-level such as GET /friends/list since they have multiple ways to show friends, such as GET /friends/ids

**Comment by basketbaseb** [comment]
there is no users controller

**Comment by basketbaseb** [comment]
d4e5cc46ca93f8b35584235a4e00d13c9f51c68a

**Comment by basketbaseb** [comment]
made a Class function User.get_users rather than just in the controller doing @users = User.all so that we can choose which data to get and return.
