### ISSUE TITLE
Organize javascript and css folder structure

### ISSUE THREAD

**Issue by natyconnor** [basketbaseb/bible-fitbit#65]
Javascript and CSS files are all over the place, and most are not needed on most pages. Some that are needed don't get loaded when they're needed without a refresh. Asset pipeline is just a mess. Need to figure this out.

Some resources:
http://railsapps.github.io/rails-javascript-include-external.html but pretty old
http://stackoverflow.com/questions/12233081/how-to-organize-javascript-in-rails-project some ideas
http://code.tutsplus.com/tutorials/using-unobtrusive-javascript-and-ajax-with-rails-3--net-15243 More proper way of using javascript in rails

http://guides.rubyonrails.org/asset_pipeline.html We all might need to understand this better

**Comment by natyconnor** [comment]
http://stackoverflow.com/questions/17664802/heroku-does-not-precompile-assets-when-deploying

Info on getting Heroku to precompile for us, so we don't have to do it locally. @basketbaseb

**Comment by basketbaseb** [comment]
rails automatically precompiles application.js, application.css and any other non-js or non-css file under app/assets/. 

You would use config.assets.precompile if you have additional assets to include like
`config.assets.precompile += ['admin.js', 'admin.css', 'swfObject.js']`

**Comment by basketbaseb** [comment]
Also...

You should use app/assets for files that must undergo some pre-processing before they are served.
In production, Rails precompiles these files to public/assets by default. The precompiled copies are then served as static assets by the web server. The files in app/assets are never served directly in production.

So it seems like anything we place in app/assets gets precompiled to public/assets automatically.

**Comment by basketbaseb** [comment]
maybe if we enable css compression when we deploy, our web app will deploy faster.
```
config.assets.css_compressor = :sass 
```
is currently commented out in production.rb. Will need to test it out.

**Comment by natyconnor** [comment]
Except heroku isn't doing it for us since it doesn't support it on Rails 4. We have the rails_12factor gem but that doesn't seem to do it. Other people say to set `config.serve_static_files = true` in production.rb Right now it's `config.serve_static_files = ENV['RAILS_SERVE_STATIC_FILES'].present?`. Maybe we should set that to true, or check what Heroku returns.

**Comment by basketbaseb** [comment]
RAILS_SERVE_STATIC_FILES: enabled

when i run heroku config

**Comment by natyconnor** [comment]
https://devcenter.heroku.com/articles/getting-started-with-rails4#heroku-gems

I think we've covered most of this but might want to look at some stuff like using `puma` and a `procfile` for better speed. Might want to check the asset pipeline section too.

**Comment by natyconnor** [comment]
Also, we have `config.assets.compile = true`. http://stackoverflow.com/questions/8821864/config-assets-compile-true-in-rails-production-why-not seems to say we shouldn't have that on for performance reasons.

**Comment by basketbaseb** [comment]
If we organize our javascript with subfolders under /app/assets/javascripts and within each subfolder we have its own manifest file which requires that directories .js files, and we add that manifest file to the precompile list and in our views we simply include that javascript file and we don't deal with the application.js then I think we should be able to have page specific javascripts.

assets
  javascripts
    admin
        admin.js
        a1.js
    client
       client.js
        c1.js

admin.js looks like this:
//
//= require jquery
//= require jquery_ujs
//= require a1

And since the application.js isn't requiring admin.js...then I don't think it will be included in our application.js

**Comment by natyconnor** [comment]
Yes `//= require_tree .` will include everything. But if we put files we want to always be available into a sub folder, we can do `//= require_tree ./folder` and then only that entire folder will be available everywhere.

**Comment by mlen1990** [comment]
Oh I didn't know you could do that with require_tree ./folder. Can we do that?

**Comment by basketbaseb** [comment]
yeah we can do that

//= require_tree . just refers to the current directory it's on

**Comment by basketbaseb** [comment]
Having javascripts and css organized based in terms of views they are used for makes sense. We definitely don't want js and css files to load on pages that don't use them. 

So I will group js and css files in subdirectories under app/assets. I will remove //= require_tree . from application.js and application.css including only those files which make sense such as jquery and bootstrap. I will add all other files to our precompile asset list and rather than adding each one, I will make sub-manifest files as noted in earlier comment.

**Comment by natyconnor** [comment]
What if we need a js file on multiple pages but not all? For example, we might want to be able to search to add friends from the home page, as well as the friends page. We wouldn't duplicate files. Should we just explicitly include javascript that isn't part of that view but needs to be used?

**Comment by basketbaseb** [comment]
can you just put it in a variable in the js file and then in the view call it?

**Comment by mlen1990** [comment]
This is pretty much done. Can we close this issue?

**Comment by natyconnor** [comment]
Yeah, I say close it for now. We may have to revisit this, but we can just reopen when that time comes.
